---
title: "Joining Gapminder Data"
author: "Your name"
output: github_document
---

# Get the original data

```{r, echo = TRUE}
library(tidyverse)
library(gapminder)

gapminder
```

# Import the HIV data

```{r}
library(readr)
hiv <- read_csv("data/gapminder_hiv.csv")

```

# What is the relationship between HIV prevalence and life expectancy?

```{r}
#do inner join to add rate column
inner_join(gapminder, hiv) %>% 
  ggplot(aes(hivRate, lifeExp)) + geom_point()+ geom_smooth() + scale_x_log10() +labs(title = "Relationship Between HIV Prevalence and Life Expectancy", x = "HIV Prevalence", y = "Life Expectancy")

```

# Which continents have the most countries with missing HIV data?

```{r}
left_join(gapminder, hiv) %>%
  filter(is.na(hivRate))%>%
  count(continent) %>%
  ggplot(aes(reorder(continent, -n), n)) + geom_col()+ labs(title = "Missing Observations by Country", x = "Continent", y = "Number of Missing Observations")



```


## Session info

```{r, echo = TRUE}
devtools::session_info()
```


